// Stand-in for the `specialists` directory service (§4, §6.2). In the real product this
// is sourced from manual curation + public aggregation + specialist self-serve claiming.
// Here it's a fixed, curated Dublin-launch dataset.

export const SPECIALTIES = [
  'Cardiology',
  'Dermatology',
  'Gynaecology',
  'Orthopaedics',
  'ENT',
  'Physiotherapy',
  'Gastroenterology',
  'Endocrinology',
];

export const SPECIALISTS = [
  {
    id: 'sp-01',
    name: 'Dr. Aoife Ní Bhriain',
    clinic: 'Blackrock Heart Clinic',
    specialty: 'Cardiology',
    area: 'Dublin 4',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 180,
    typicalFeeMax: 220,
    avgRating: 4.8,
    reviewCount: 63,
    nextAvailable: 'Tue, 3 days',
    category: 'consultant',
  },
  {
    id: 'sp-02',
    name: 'Dr. Marcus Doyle',
    clinic: 'St. James Cardiac Suite',
    specialty: 'Cardiology',
    area: 'Dublin 8',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': false },
    typicalFeeMin: 200,
    typicalFeeMax: 250,
    avgRating: 4.6,
    reviewCount: 41,
    nextAvailable: 'Mon, 9 days',
    category: 'consultant',
  },
  {
    id: 'sp-03',
    name: 'Dr. Sarah Lee',
    clinic: 'Grafton Dermatology',
    specialty: 'Dermatology',
    area: 'Dublin 2',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 140,
    typicalFeeMax: 180,
    avgRating: 4.9,
    reviewCount: 112,
    nextAvailable: 'Thu, 2 days',
    category: 'consultant',
  },
  {
    id: 'sp-04',
    name: 'Dr. Michael Brown',
    clinic: 'Derma Clinic Dublin',
    specialty: 'Dermatology',
    area: 'Dublin 6',
    insurerRecognition: { Laya: true, Vhi: false, 'Irish Life': true },
    typicalFeeMin: 130,
    typicalFeeMax: 170,
    avgRating: 4.5,
    reviewCount: 38,
    nextAvailable: 'Wed, 6 days',
    category: 'consultant',
  },
  {
    id: 'sp-05',
    name: 'Dr. Fiona Walsh',
    clinic: 'Merrion Women\'s Health',
    specialty: 'Gynaecology',
    area: 'Dublin 2',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 160,
    typicalFeeMax: 210,
    avgRating: 4.9,
    reviewCount: 87,
    nextAvailable: 'Mon, 5 days',
    category: 'consultant',
  },
  {
    id: 'sp-06',
    name: 'Dr. Emer Coyle',
    clinic: 'Rotunda Private Clinic',
    specialty: 'Gynaecology',
    area: 'Dublin 1',
    insurerRecognition: { Laya: false, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 170,
    typicalFeeMax: 220,
    avgRating: 4.7,
    reviewCount: 54,
    nextAvailable: 'Fri, 8 days',
    category: 'consultant',
  },
  {
    id: 'sp-07',
    name: 'Mr. Conor Fitzgerald',
    clinic: 'Santry Orthopaedic Clinic',
    specialty: 'Orthopaedics',
    area: 'Dublin 9',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 190,
    typicalFeeMax: 240,
    avgRating: 4.7,
    reviewCount: 71,
    nextAvailable: 'Tue, 4 days',
    category: 'consultant',
  },
  {
    id: 'sp-08',
    name: 'Dr. Niamh O\'Sullivan',
    clinic: 'City ENT Clinic',
    specialty: 'ENT',
    area: 'Dublin 4',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': false },
    typicalFeeMin: 150,
    typicalFeeMax: 190,
    avgRating: 4.6,
    reviewCount: 49,
    nextAvailable: 'Thu, 7 days',
    category: 'consultant',
  },
  {
    id: 'sp-09',
    name: 'David Keane',
    clinic: 'Rathmines Physio Studio',
    specialty: 'Physiotherapy',
    area: 'Dublin 6',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 60,
    typicalFeeMax: 80,
    avgRating: 4.8,
    reviewCount: 134,
    nextAvailable: 'Mon, 2 days',
    category: 'physio',
  },
  {
    id: 'sp-10',
    name: 'Dr. Alan Byrne',
    clinic: 'Baggot Street Gastro Clinic',
    specialty: 'Gastroenterology',
    area: 'Dublin 4',
    insurerRecognition: { Laya: true, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 200,
    typicalFeeMax: 260,
    avgRating: 4.5,
    reviewCount: 29,
    nextAvailable: 'Wed, 10 days',
    category: 'consultant',
  },
  {
    id: 'sp-11',
    name: 'Dr. Grace Molloy',
    clinic: 'Leeson Street Endocrine Clinic',
    specialty: 'Endocrinology',
    area: 'Dublin 2',
    insurerRecognition: { Laya: false, Vhi: true, 'Irish Life': true },
    typicalFeeMin: 180,
    typicalFeeMax: 230,
    avgRating: 4.7,
    reviewCount: 33,
    nextAvailable: 'Fri, 12 days',
    category: 'consultant',
  },
  {
    id: 'sp-12',
    name: 'Dr. Paul Nolan',
    clinic: 'Dundrum Cardiology Rooms',
    specialty: 'Cardiology',
    area: 'Dublin 14',
    insurerRecognition: { Laya: true, Vhi: false, 'Irish Life': true },
    typicalFeeMin: 175,
    typicalFeeMax: 215,
    avgRating: 4.4,
    reviewCount: 22,
    nextAvailable: 'Mon, 6 days',
    category: 'consultant',
  },
];

export function findSpecialistsBySpecialty(specialty) {
  return SPECIALISTS.filter((s) => s.specialty.toLowerCase() === (specialty ?? '').toLowerCase());
}

export function getSpecialist(id) {
  return SPECIALISTS.find((s) => s.id === id) ?? null;
}
